### ISSUE TITLE
Cannot use in Nextjs

### ISSUE THREAD

**Issue by LawrenceWlt** [sayumani/copytoclipboard#1]
The following error occurs;

`./node_modules/react-toastify/dist/ReactToastify.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\copy-to-clipboard-react\dist\index.modern.js`

Would you please consider publishing a compiled version of the dependency.? Thanks

**Comment by sayumani** [comment]
If you can fix this , please fix and raise a merge request

**Comment by sayumani** [comment]
your pull request merged, new version is published to npm.
