### ISSUE TITLE
Wrong import in the documentation

### ISSUE THREAD

**Issue by LawrenceWlt** [sayumani/copytoclipboard#2]
The documentation is wrong on the import statements. 
It has 

`import CopyToCLipBoard from 'copytoclipboard'`
`import 'copytoclipboard/dist/index.css'`

The correct imports are 

`import CopyToCLipBoard from "copy-to-clipboard-react";`
`import "copy-to-clipboard-react/dist/index.css";`

**Comment by sayumani** [comment]
new version released with updated documentation
